"""Public Pydantic contracts for the HCMAI HTTP and WebSocket APIs."""


from .frames import CatalogTranscriptSegment, FrameCatalogEntry, FrameInspectionResponse
from .filter import FilterMetadataFilters, FilterRequest, FilterResponse, FilterResult
from .kis import (
    EventPatch,
    GlobalRewriteOperation,
    InitialResolveOperation,
    KISIntent,
    KISOperation,
    KISOperationSummary,
    KISSearchRequest,
    KISSearchResponse,
    PatchEventsOperation,
    SearchOnlyOperation,
)
from .latency import SearchLatency
from .search import (
    ImageSearchResponse,
    SearchResult,
    SearchResultMetadata,
)
from .trake import TRAKEPath, TRAKERequest, TRAKEResponse
from .event_trail import (
    ApproveAction,
    ClearAnchorAction,
    ClearWindowAction,
    DeclineAction,
    EventTrailActionContract,
    EventTrailActionRequest,
    EventTrailCandidateDiff,
    EventTrailEventCandidate,
    EventTrailOpenRequest,
    EventTrailStateResponse,
    EventTrailSubmissionSelection,
    EventTrailTransition,
    SetWindowAction,
    UndoAction,
    UseFrameAction,
)
from .vbs import (
    VbsDirectSubmissionNotRecorded,
    VbsDirectSubmissionOutcome,
    VbsDirectSubmissionRecorded,
    VbsDirectSubmissionRequest,
    VbsDirectSubmissionUnknown,
    VbsSessionConnectRequest,
    VbsSessionStatus,
    VbsTaskResponse,
    VbsTemporalAnswer,
    VbsTextAnswer,
)


__all__ = [
    "CatalogTranscriptSegment",
    "FrameCatalogEntry",
    "FrameInspectionResponse",
    "FilterMetadataFilters",
    "FilterRequest",
    "FilterResponse",
    "FilterResult",
    "ImageSearchResponse",
    "EventPatch",
    "GlobalRewriteOperation",
    "InitialResolveOperation",
    "KISIntent",
    "KISOperation",
    "KISOperationSummary",
    "KISSearchRequest",
    "KISSearchResponse",
    "PatchEventsOperation",
    "SearchOnlyOperation",
    "SearchLatency",
    "SearchResult",
    "SearchResultMetadata",
    "VbsDirectSubmissionNotRecorded",
    "VbsDirectSubmissionOutcome",
    "VbsDirectSubmissionRecorded",
    "VbsDirectSubmissionRequest",
    "VbsDirectSubmissionUnknown",
    "VbsSessionConnectRequest",
    "VbsSessionStatus",
    "VbsTaskResponse",
    "VbsTemporalAnswer",
    "VbsTextAnswer",
    "TRAKEPath",
    "TRAKERequest",
    "TRAKEResponse",
    "ApproveAction",
    "ClearAnchorAction",
    "ClearWindowAction",
    "DeclineAction",
    "EventTrailActionContract",
    "EventTrailActionRequest",
    "EventTrailCandidateDiff",
    "EventTrailEventCandidate",
    "EventTrailOpenRequest",
    "EventTrailStateResponse",
    "EventTrailSubmissionSelection",
    "EventTrailTransition",
    "SetWindowAction",
    "UndoAction",
    "UseFrameAction",
]
