# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hcmai.retrieval_service.proto import retrieval_pb2 as hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hcmai/retrieval_service/proto/retrieval_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RetrievalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/hcmai.retrieval.v1.RetrievalService/GetCapabilities',
                request_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.SearchPlan = channel.unary_unary(
                '/hcmai.retrieval.v1.RetrievalService/SearchPlan',
                request_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SearchPlanRequest.SerializeToString,
                response_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.TemporalSearchArtifact.FromString,
                _registered_method=True)
        self.SearchEvents = channel.unary_unary(
                '/hcmai.retrieval.v1.RetrievalService/SearchEvents',
                request_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SearchEventsRequest.SerializeToString,
                response_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.TemporalSearchResult.FromString,
                _registered_method=True)
        self.ScoreVideo = channel.unary_unary(
                '/hcmai.retrieval.v1.RetrievalService/ScoreVideo',
                request_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.ScoreVideoRequest.SerializeToString,
                response_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SelectedVideoScore.FromString,
                _registered_method=True)
        self.SearchImage = channel.unary_unary(
                '/hcmai.retrieval.v1.RetrievalService/SearchImage',
                request_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SearchImageRequest.SerializeToString,
                response_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.ImageSearchCandidates.FromString,
                _registered_method=True)


class RetrievalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'SearchPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPlan,
                    request_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SearchPlanRequest.FromString,
                    response_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.TemporalSearchArtifact.SerializeToString,
            ),
            'SearchEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEvents,
                    request_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SearchEventsRequest.FromString,
                    response_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.TemporalSearchResult.SerializeToString,
            ),
            'ScoreVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreVideo,
                    request_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.ScoreVideoRequest.FromString,
                    response_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SelectedVideoScore.SerializeToString,
            ),
            'SearchImage': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchImage,
                    request_deserializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SearchImageRequest.FromString,
                    response_serializer=hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.ImageSearchCandidates.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hcmai.retrieval.v1.RetrievalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hcmai.retrieval.v1.RetrievalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrievalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcmai.retrieval.v1.RetrievalService/GetCapabilities',
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.GetCapabilitiesRequest.SerializeToString,
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcmai.retrieval.v1.RetrievalService/SearchPlan',
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SearchPlanRequest.SerializeToString,
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.TemporalSearchArtifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcmai.retrieval.v1.RetrievalService/SearchEvents',
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SearchEventsRequest.SerializeToString,
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.TemporalSearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcmai.retrieval.v1.RetrievalService/ScoreVideo',
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.ScoreVideoRequest.SerializeToString,
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SelectedVideoScore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcmai.retrieval.v1.RetrievalService/SearchImage',
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.SearchImageRequest.SerializeToString,
            hcmai_dot_retrieval__service_dot_proto_dot_retrieval__pb2.ImageSearchCandidates.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
